openapi: 3.0.1
info:
  title: Star Wars
  description: ''
  version: '1.0'
servers:
  - url: https://apim-lab-pk.azure-api.net
paths:
  /people/:
    get:
      summary: GetPeople
      operationId: getpeople
      responses:
        '200':
          description: 
  '/people/{id}/':
    get:
      summary: GetPeopleById
      operationId: getpeoplebyid
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: ''
      responses:
        '200':
          description: 
  /films/:
    get:
      summary: GetFilms
      operationId: getfilms
      responses:
        '200':
          description: 
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]